# Generated by Django 5.2.5 on 2025-12-31 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='酒店ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='酒店名称')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='品牌')),
                ('business_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='商业区')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='HotelPOI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('poiname', models.CharField(max_length=255, verbose_name='POI名称')),
            ],
            options={
                'db_table': 'hotel_poi',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomOffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='房型')),
                ('offer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='报价名称')),
                ('room_price_origin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='原价')),
                ('room_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='优惠价')),
                ('offer_discount_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='折扣文案')),
                ('offer_breakfast_policy', models.CharField(blank=True, max_length=255, null=True, verbose_name='早餐政策')),
            ],
            options={
                'db_table': 'hotel_room_offer',
            },
        ),
        migrations.CreateModel(
            name='HotelCommentStar',
            fields=[
                ('hotel', models.OneToOneField(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comment_star', serialize=False, to='api.hotel')),
                ('experiencescore_mix', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='综合体验分')),
            ],
            options={
                'db_table': 'hotel_comment_star',
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['brand'], name='idx_hotel_brand'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['business_area'], name='idx_hotel_bizarea'),
        ),
        migrations.AddField(
            model_name='hotelpoi',
            name='hotel',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='api.hotel'),
        ),
        migrations.AddField(
            model_name='hotelroomoffer',
            name='hotel',
            field=models.ForeignKey(db_column='hotel_id', on_delete=django.db.models.deletion.CASCADE, related_name='room_offers', to='api.hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelpoi',
            index=models.Index(fields=['hotel'], name='idx_poi_hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelpoi',
            index=models.Index(fields=['poiname'], name='idx_poi_name'),
        ),
        migrations.AddConstraint(
            model_name='hotelpoi',
            constraint=models.UniqueConstraint(fields=('hotel', 'poiname'), name='uniq_hotel_poiname'),
        ),
        migrations.AddIndex(
            model_name='hotelroomoffer',
            index=models.Index(fields=['hotel'], name='idx_offer_hotel'),
        ),
        migrations.AddIndex(
            model_name='hotelroomoffer',
            index=models.Index(fields=['hotel', 'room_type'], name='idx_offer_hotel_roomtype'),
        ),
        migrations.AddIndex(
            model_name='hotelroomoffer',
            index=models.Index(fields=['hotel', 'room_type', 'offer_name'], name='idx_offer_hotel_room_offer'),
        ),
        migrations.AddIndex(
            model_name='hotelroomoffer',
            index=models.Index(fields=['room_offer_price'], name='idx_offer_price'),
        ),
    ]
