# Generated by Django 6.0.1 on 2026-01-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversationsession_apiclient_message_usagerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiclient',
            name='user',
        ),
        migrations.CreateModel(
            name='AdpChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=128)),
                ('visitor_biz_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('app', models.CharField(default='s', max_length=32)),
                ('user_question', models.TextField()),
                ('model_answer', models.TextField(blank=True, default='')),
                ('feedback', models.BooleanField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='api_adpchat_session_d64b16_idx')],
            },
        ),
    ]
